# Generated by Django 4.0.4 on 2022-04-18 07:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SlotTimings',
            fields=[
                ('slot_timing_id', models.AutoField(primary_key=True, serialize=False)),
                ('slot_from_time', models.TimeField()),
                ('slot_to_time', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Slot',
            fields=[
                ('slot_id', models.AutoField(primary_key=True, serialize=False)),
                ('slot_date', models.DateField()),
                ('slot_timing', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='billboard.slottimings')),
            ],
        ),
    ]
