# Generated by Django 4.0.4 on 2022-04-18 11:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('billboard', '0002_billboard'),
    ]

    operations = [
        migrations.AddField(
            model_name='slot',
            name='billboard',
            field=models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.PROTECT, to='billboard.billboard'),
        ),
        migrations.AddField(
            model_name='slot',
            name='company',
            field=models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
    ]
