# Generated by Django 4.0.4 on 2022-06-17 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billboard', '0005_alter_billboard_table_alter_slot_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='slot',
            name='video_url',
            field=models.URLField(default=None),
        ),
    ]
